### ISSUE TITLE
KVK/PVK field mismatch ?

### ISSUE THREAD

**Issue by jorisoft** [Kaupisch-IT/eGK-KVK#4]
Reading a PVK I get the value "0010" in the property KVKResult.VersichertenStatus. But this value "0010" is the value of the "Personenkreis" which is also printed on the card itself. You also have the field KvkResult.StatusErgänzung which has a "1" for my card (which I assume) is the value which should be in KVKResult.VersichertenStatus (as I am a "Mitglied"). Maybe you mismatched the field offsets for those two fields ?

**Comment by Kaupisch-IT** [comment]
The KVK part was developed according to [MKT - Anhang 3:  MKT-Anforderungen für Versichertenkarten](https://www.teletrust.de/fileadmin/_migrated/content_uploads/MKT1-0_A3.pdf).  
When decoding, no difference is made between KVK or PKV Card. According to the "Technische Spezifikation der Card für Privatversicherte" (provided by pkv.de), the data structure of the application file is as follows;

<table>
<tr><th>KVK (Krankenversichertenkarte)</th><th>PKV (Card für Privatversicherte)</th></tr>
<tr>
<td>

![KVK](https://user-images.githubusercontent.com/54144666/124274008-09e08b80-db41-11eb-82b9-19149a13f8d5.PNG)

</td>
<td>

![PKV](https://user-images.githubusercontent.com/54144666/124274117-2a104a80-db41-11eb-9f71-0ccbb86f01db.PNG)

</td>
</tr>
</table>

To be honest: Since Verband der Privaten Krankenversicherung e.V. has provided the specification of the PVK Card only as a PDF version of a scanned document, I could not do a text diff to find any differences - for me, the data format looked exactly like that of the KVK.

Apparently there are a few **differences** after all:

| tag        | length (KVK)  | value (KVK)  |	value (PKV) | length (PKV) | 
| ------------- |:-------------:|-----:|:------|:---:|
| `'80`' | 2-28	| **KrankenKassenName**	| **NameundNummerPKV-Unternehmen**	| 2-28	|
| `'81`' | 7		| **KrankenKassenNummer**	| Konstante 1 (ausgenullt) 	| 7	|
| `'8F`' | 5		| **VKNR** | Konstante 2 (ausgenullt) 	| 5	|
| `'82`' | 6-12	| *VersichertenNummer*	| *VersicherungsNummer* 	| 6-12	|
| `'83`' | 1 oder 4| 	**VersichertenStatus**	| **PersonenNummer** 	| 	4|
| `'90`' | 1-3	| **StatusErgänzung** | Konstante 3 	| 1	|
| `'84`' | 2-15	| Titel 	|  Titel | 2-15	|
| `'85`' | 1-28	| VorName 	| VorName 	| 1-28	|
| `'86`' | 1-15	| NamensZusatz/VorsatzWort 	| NamensZusatz/VorsatzWort 	| 1-15	|
| `'87`' | 2-28	| FamilienName	| FamilienName 	| 2-28	|
| `'88`' | 8	| GeburtsDatum	| GeburtsDateum 	| 8	|
| `'89`' | 2-28	| StraßenName&HausNummer	|  StraßenName&HausNummer	| 2-28	|
| `'8A`' | 1-3	| WohnsitzLänderCode	| WonsitzLänderCode 	| 1-3	|
| `'8B`' | 4-7	| Postleitzahl	|  Postleitzahl	| 4-7	|
| `'8C`' | 2-23	| OrtsName|  OrtsName	| 2-22	|
| `'8D`' | 4	| GültigkeitsDatum	|  GültigkeitsDatum	| 4	|

Currently, `KvkResult.VersichertenStatus` and `KvkResult.StatusErgänzung` is defined as follows:

```csharp
/// <summary> 
/// Gibt den Versichertenstatus an. 
/// 1 = Versicherungspflichtige und -berechtigte
/// 3 = Familienversicherte
/// 5 = Rentner in der Krankenversicherung der Rentner und deren familienversicherten Angehörige
/// </summary>
public string VersichertenStatus
	=> this[0x83];
	
/// <summary> Gibt das Kennzeichen bei Teilnehmern an einem Disease-Management-Programm an. </summary>
public string StatusErgänzung
	=> this[0x90];
```

**Comment by jorisoft** [comment]
I think you are right, you query the correct field, in your method header you only mention 1,3,5 as possible values and most of the times these are right, but as the spec tells, the field could also be 4 chars long (which is the case for my card) containing 0010. I know that 0010 has the same meaning as 1 has for only one letter content (=Mitglied), do you know where I can look up the 4 letter values for Renter and Familienversicherte ?

Thanks for your help so far !

**Comment by Kaupisch-IT** [comment]
> in your method header you only mention 1,3,5 as possible values and most of the times these are right

Yeah, this comment is quite KVK-specific. These values can be found in [Technische Spezifikation der Versichertenkarte - Versichertenstatus](https://www.gkv-spitzenverband.de/media/dokumente/krankenversicherung_1/telematik/versichertenkarte/Techn_Spezifik_der_VersKarte_25_11_2009_Version_2_08.pdf) (page 51). However, KVKs are no longer in use, so these values should have become obsolete.

For PKVs - I don't know exactly what a *Personennummer* can look like. The only part of *Technische Spezifikation der Card für Privatversicherte* mentioning it is:

> Versicherungsnummer mit maximal 12 Stellen (Vertragsnummer)
> Personennummer mit maximal 4 Stellen (Vertragsunternummer der versicherten Person)

For "StatusErgänzung | Konstante 3": *Technische Spezifikation der Card für Privatversicherte - Anlage 1a" states:

![image](https://user-images.githubusercontent.com/54144666/124280827-6f387a80-db49-11eb-988f-a39024999218.png)

Apparently, `KvkResult.StatusErgänzung` is always "1" if a PVK Card is present.

**Comment by Kaupisch-IT** [comment]
Hm, since there are indeed small differences in the data format of the KVK and PVK-Card and the KVK itself is also outdated, we should also introduce a separate PkvResult and mark the KvkResult obsolete, right? What do you think?

**Comment by jorisoft** [comment]
Thank you for the update. Do you have any idea were to get possible values for the Personennummer property ? I would like to know how they code Renter and Familienversicherter in case they use 4 chars.... I could not find anything on my google search about it

**Comment by Kaupisch-IT** [comment]
As far as I know, the concept of *Versichertenstatus* only exits for gesetzliche Krankenversicherungen (eGK). Since the PKV-Card is only issued by privaten Krankenversicherungen, there shouldn't be such distinction.

[PKV-Rahmenvereinbarung](https://www.pkv-leistungserbringer.info/index.php?_=/user_upload/2019-01-29_rv17c_PKV-DKG_Gesamtdoku.pdf&L=0&dl=250):
> Der  Personennummer  (Schlüssel A)  ist  eine  von  dem  Versicherungsunternehmen  vergebene Nummer zur eindeutigen Identifikation einer versicherten Person innerhalb eines Versicherungsvertrages. Sie ist auf der Card für Privatversicherte gespeichert und ausgewiesen. Sollte die Personennummer bei der Aufnahme nicht zu ermitteln sein (Card für Privatversicherte liegt nicht vor) oder handelt es sich um die Behandlung eines erkrankten Neugeborenen (eigener Fall), kann der Aufnahmesatz  ohne  Personennummer  übertragen  werden.  In  diesem  Fall  ist  das  Geburtsdatum des  Versicherten  anzugeben.  Die  Personennummer  wird  von  dem  Versicherungsunternehmen mit  der  Bestätigung  des  Versichertenstatus  gemeldet,  sie  ist  in  allen  folgenden  Nachrichten  zu verwenden.

**Comment by jorisoft** [comment]
Thank you for your information. In case I will discover more different codes for Perseonennummer I will send you a note for your reference.

**Comment by Kaupisch-IT** [comment]
FYI: The data stored on the offical PKV-Card for testing purposes ("Testkarte", available via [pkv.de](https://www.pkv.de/verband/kontakt-mit-ansprechpersonen/)) is as follows:  
(Personennummer is `0002`)
```json
"PkvResult": { 
    "KrankenKassenName": "INTER KV AG      4145", 
    "Konstante1": "0000000", 
    "VKNR": "00000", 
    "VersicherungsNummer": "080089030", 
    "PersonenNummer": "0002", 
    "Konstante3": "1", 
    "Titel": null, 
    "VorName": "Brigitte", 
    "NamensZusatz_VorsatzWort": null, 
    "FamilienName": "Kahn", 
    "GeburtsDatum": "01051983", 
    "StraßenName_HausNummer": "A 5 9", 
    "WohnsitzLänderCode": null, 
    "Postleitzahl": "68159", 
    "OrtsName": "Mannheim", 
    "GültigkeitsDatum": "0418" 
  },
```

**Comment by jorisoft** [comment]
Thank you very muh, but do you know the interpretation of 0002 ? On my own card it says 0001 (Mitglied)

**Comment by Kaupisch-IT** [comment]
As far as I understand, it's just an ID within a Versicherungsvertrag. Imagine having a (one) Familienversicherung: The `VersicherungsNummer` is all the same for you, your partner, and your child; whereas every person has an own, unique `PersonenNummer`.  
VersicherungsNummer `12345` + PersonenNummer `0001` = you  
VersicherungsNummer `12345` + PersonenNummer `0002` = your partner  
VersicherungsNummer `12345` + PersonenNummer `0003` = your child

**Comment by jorisoft** [comment]
That would make sense thank you
